### PR TITLE
Allow to set package version

### LINKED ISSUE #35: No way to set desired openssl package version
May I suggest adding an $ensure paramter similar to:

```puppet
class openssl (
  $package_ensure => present,
){
}

class openssl::packages {
  package { 'openssl':
    ensure => $openssl::package_ensure,
  }
}
```

If no one has any objection, I will make the change and submit a pull request.

Any thoughts?

### PR DESCRIPTION
**Pull request by edestecd**
Fixes #35

### CODE REVIEW

**Comment by edestecd** [comment]
@raphink any comment on this?  Seemed like you were good with this change...

**Comment by raphink** [comment]
I'm fine with it, sorry for the lag.

**Comment by raphink** [comment]
Could you just document the parameters in README.md please?

**Comment by edestecd** [comment]
@raphink hows that doc?

**Comment by raphink** [comment]
Looking good, thank you.

**Pull request merged**
