### PR TITLE
Allow generating server or client only certificates.

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
One option I thought about was generalizing this to allowing users to declare extensions generically to be included with examples of how to achieve server or client only certificates (since those are common use cases of extensions). This would require users to provide their own templates, or we could add concat to attach extensions to the config file as provided by the user.

**Comment by raphink** [comment]
Can you have both `server_only` and `client_only` set to true at the same time? 

If not (which I believe), then I think a single option with an enum would be better, say `only_for => client ` or `only_for => server`.

**Comment by raphink** [comment]
@ehelms any news?

**Comment by ehelms** [comment]
I've been revisiting this, albeit slowly. I'll post some updates next week.

**Comment by raphink** [comment]
OK, great.

**Comment by raphink** [comment]
@ehelms is this still something you aim to implement?

**Comment by WetHippie** [comment]
I have my own local branch on my fork that implements just a simple flag of "is_server" that will generate server certs from the certificate chain. Would you like me to tidy up and give you a pull request?

**Comment by raphink** [comment]
@WetHippie so your branch only implements the equivalent of `server_only`?

**Comment by WetHippie** [comment]
I believe so (ie, I don't think anything else has snuck through in my branch).  For me the flag is `is_server`, in which case the code then generates the x509 cert with the -nodes option included in the command line. The changes are to the type and provider to allow for this and can be used in the shortcut too.  I'll drop in a pull request for you to have a look at.

**Comment by raphink** [comment]
@ehelms any second thoughts before @WetHippie sends his PR?

**Comment by ehelms** [comment]
Nope - all @WetHippie

**Comment by raphink** [comment]
Ok thanks

**Pull request closed without merging**
