### PR TITLE
add file permission (owner, group, mode) for all defined types

### PR DESCRIPTION
**Pull request by trefzer**
add file permissions (owner, group, mode) for all defined types

### CODE REVIEW

**Comment by raphink** [comment]
Thanks for this. 

Could you explain why this is necessary please? What is the problem with the current wrapping of the `file` resource type?

**Comment by trefzer** [comment]
Hi,
if I get that correct, you mean like it is done in  openssl::certificate::x509 line 177 to end ?

Well there's nothing wrong with that.
In my setup I like to create a key and a csr but I do not want to self sign. So there where several implementation methods available:
1.) adapt openssl::certificate::x509 with some if's
2.) add a openssl::certificate::x509_without selfsign
3.) use ssl_pkey and x509_request directly without surrounding puppet code

Well I decided for 3, which gives me the most flexibility. But I still want to adapt the file permissions (without any puppet code of course, since I use hiera with a helper class to use defines).

That's why I decided to add this to the code. Despite that I think it's a "proper" solution to have all the attributes that characterize a "thing" in one single resource call.

btw: adapt openssl::certificate::x509 is still working as expected since mode,group and owner are not mandatory so no change for any user. But the mentioned define could be simplified after merging this.

**Comment by raphink** [comment]
Thanks for the explanation. I'm a bit surprised because the PR says it aims to fix the situation, but you're saying the current situation actually works fine, so this is an improvement, right?

**Comment by trefzer** [comment]
sorry about that. definitly an enhancement. the 'fix' was automatically taken from the branch name, which follows our naming convention for branches, which does not distinguish fixes and enhancements but means 'given upstream'.

**Comment by trefzer** [comment]
could you please give a reason for closing this ?

**Pull request closed without merging**
