### PR TITLE
Manage ca-certificates package on redhat too

### LINKED ISSUE #47: ca-certificates package is available in redhat also
There is an if around the ca-certificates package.

### PR DESCRIPTION
**Pull request by edestecd**
Fixes #47

### CODE REVIEW

**Comment by edestecd** [comment]
Anyone have thoughts on this?

**Comment by edestecd** [comment]
No feedback whatsoever?

**Comment by raphink** [comment]
@mcanevet could you have a look at this please?

**Comment by mcanevet** [comment]
LGTM

**Pull request merged**
